name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  merge:
    strategy:
      fail-fast: false
      matrix:
        branch: [bugfix-2.0.x, 2.0.x]

    runs-on: ubuntu-latest

    steps:
    - name: Check out ${{ matrix.branch }}
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - name: Merge ${{ matrix.branch }}
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git fetch --unshallow
        git pull https://github.com/MarlinFirmware/Marlin ${{ matrix.branch }}
        git tag -a nightly-${{ matrix.branch }}-$(date '+%Y-%m-%d') -m "Nightly build at $(date '+%Y-%m-%d') on ${{ matrix.branch }}"
        git push --follow-tags
