name: Nightly Build

on:
  schedule:
    - cron: '0 10 * * *' # run at 10 AM UTC

jobs:
  merge:
    strategy:
      fail-fast: false
      matrix:
        branch: [bugfix-2.0.x, 2.0.x]

    runs-on: ubuntu-latest

    steps:
    - name: Check out bugfix-2.0.x
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - name: Merge ${{ matrix.branch }}
      run: |
        git pull https://github.com/MarlinFirmware/Marlin ${{ matrix.branch }}
        git add *
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git commit -m "[cron] Merged upstream changes from $(date '+%Y-%m-%d')" -a
        git push
